CREATE DATABASE authdb;
CREATE DATABASE accountdb;
CREATE DATABASE transferdb;
GRANT ALL PRIVILEGES ON DATABASE authdb TO admin;
GRANT ALL PRIVILEGES ON DATABASE accountdb TO admin;
GRANT ALL PRIVILEGES ON DATABASE transferdb TO admin;